<?php
/** Narrowly allowlisted site-administration abilities. */

if ( ! defined( 'ABSPATH' ) ) { exit; }

function samcp_register_admin_category() { if ( function_exists( 'wp_register_ability_category' ) ) { wp_register_ability_category( 'site-abilities-admin', array( 'label' => __( 'Site Administration', 'site-abilities-mcp' ), 'description' => __( 'Allowlisted settings and extension inventory; no code or arbitrary option editing.', 'site-abilities-mcp' ) ) ); } }
add_action( 'wp_abilities_api_categories_init', 'samcp_register_admin_category' );

function samcp_safe_setting_keys() { return array( 'blogname', 'blogdescription', 'timezone_string', 'date_format', 'time_format', 'start_of_week', 'posts_per_page', 'show_on_front', 'page_on_front', 'page_for_posts' ); }
function samcp_settings_schema() { return array( 'type' => 'object', 'required' => array_merge( samcp_safe_setting_keys(), array( 'settings_sha256' ) ), 'properties' => array( 'blogname' => array( 'type' => 'string' ), 'blogdescription' => array( 'type' => 'string' ), 'timezone_string' => array( 'type' => 'string' ), 'date_format' => array( 'type' => 'string' ), 'time_format' => array( 'type' => 'string' ), 'start_of_week' => array( 'type' => 'integer' ), 'posts_per_page' => array( 'type' => 'integer' ), 'show_on_front' => array( 'type' => 'string' ), 'page_on_front' => array( 'type' => 'integer' ), 'page_for_posts' => array( 'type' => 'integer' ), 'settings_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'snapshot_id' => array( 'type' => 'string' ) ) ); }
function samcp_register_admin_abilities() {
	if ( ! function_exists( 'wp_register_ability' ) ) { return; }
	wp_register_ability( 'site-abilities/get-site-settings', array( 'label' => __( 'Read safe site settings', 'site-abilities-mcp' ), 'description' => __( 'Reads only the allowlisted identity, time, reading and homepage settings.', 'site-abilities-mcp' ), 'category' => 'site-abilities-admin', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false ), 'output_schema' => samcp_settings_schema(), 'execute_callback' => 'samcp_get_site_settings', 'permission_callback' => 'samcp_can_manage_options', 'meta' => samcp_ability_meta( true, false, true ) ) );
	$setting_properties = samcp_settings_schema()['properties']; unset( $setting_properties['settings_sha256'], $setting_properties['snapshot_id'] );
	wp_register_ability( 'site-abilities/update-site-settings', array( 'label' => __( 'Update safe site settings', 'site-abilities-mcp' ), 'description' => __( 'Updates only allowlisted settings after a state checksum, explicit confirmation and a recoverable snapshot. Arbitrary options are impossible.', 'site-abilities-mcp' ), 'category' => 'site-abilities-admin', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'expected_settings_sha256', 'confirmation' ), 'properties' => array_merge( array( 'expected_settings_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'confirmation' => array( 'type' => 'string', 'enum' => array( 'UPDATE_SITE_SETTINGS' ) ) ), $setting_properties ) ), 'output_schema' => samcp_settings_schema(), 'execute_callback' => 'samcp_update_site_settings', 'permission_callback' => 'samcp_can_manage_options', 'meta' => samcp_ability_meta( false, true, false ) ) );
	wp_register_ability( 'site-abilities/restore-site-settings', array( 'label' => __( 'Restore safe site settings', 'site-abilities-mcp' ), 'description' => __( 'Restores a settings snapshot after current-state validation and explicit confirmation.', 'site-abilities-mcp' ), 'category' => 'site-abilities-admin', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'snapshot_id', 'expected_settings_sha256', 'confirmation' ), 'properties' => array( 'snapshot_id' => array( 'type' => 'string', 'pattern' => '^[a-zA-Z0-9-]{8,64}$' ), 'expected_settings_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'confirmation' => array( 'type' => 'string', 'enum' => array( 'RESTORE_SITE_SETTINGS' ) ) ) ), 'output_schema' => samcp_settings_schema(), 'execute_callback' => 'samcp_restore_site_settings', 'permission_callback' => 'samcp_can_manage_options', 'meta' => samcp_ability_meta( false, true, false ) ) );
	wp_register_ability( 'site-abilities/list-plugins', array( 'label' => __( 'List plugins', 'site-abilities-mcp' ), 'description' => __( 'Lists installed plugins, versions and activation status without changing them.', 'site-abilities-mcp' ), 'category' => 'site-abilities-admin', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false ), 'output_schema' => array( 'type' => 'object', 'properties' => array( 'plugins_sha256' => array( 'type' => 'string' ), 'plugins' => array( 'type' => 'array', 'items' => array( 'type' => 'object' ) ) ) ), 'execute_callback' => 'samcp_list_plugins', 'permission_callback' => 'samcp_can_activate_plugins', 'meta' => samcp_ability_meta( true, false, true ) ) );
	wp_register_ability( 'site-abilities/set-plugin-state', array( 'label' => __( 'Activate or deactivate plugin', 'site-abilities-mcp' ), 'description' => __( 'Activates or deactivates an installed non-protected plugin after inventory validation and explicit confirmation. Installation, updates and code editing are unavailable.', 'site-abilities-mcp' ), 'category' => 'site-abilities-admin', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'plugin_file', 'state', 'expected_plugins_sha256', 'confirmation' ), 'properties' => array( 'plugin_file' => array( 'type' => 'string', 'maxLength' => 500 ), 'state' => array( 'type' => 'string', 'enum' => array( 'active', 'inactive' ) ), 'expected_plugins_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'confirmation' => array( 'type' => 'string', 'enum' => array( 'SET_PLUGIN_STATE' ) ) ) ), 'output_schema' => array( 'type' => 'object', 'properties' => array( 'plugin_file' => array( 'type' => 'string' ), 'state' => array( 'type' => 'string' ), 'plugins_sha256' => array( 'type' => 'string' ) ) ), 'execute_callback' => 'samcp_set_plugin_state', 'permission_callback' => 'samcp_can_activate_plugins', 'meta' => samcp_ability_meta( false, true, false ) ) );
	wp_register_ability( 'site-abilities/list-themes', array( 'label' => __( 'List themes', 'site-abilities-mcp' ), 'description' => __( 'Lists installed themes and the active stylesheet. Theme switching, installation and file editing are intentionally unavailable.', 'site-abilities-mcp' ), 'category' => 'site-abilities-admin', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false ), 'output_schema' => array( 'type' => 'array', 'items' => array( 'type' => 'object' ) ), 'execute_callback' => 'samcp_list_themes', 'permission_callback' => 'samcp_can_switch_themes', 'meta' => samcp_ability_meta( true, false, true ) ) );
}
add_action( 'wp_abilities_api_init', 'samcp_register_admin_abilities' );

function samcp_can_manage_options() { return current_user_can( 'manage_options' ); }
function samcp_can_activate_plugins() { return current_user_can( 'activate_plugins' ); }
function samcp_can_switch_themes() { return current_user_can( 'switch_themes' ); }
function samcp_setting_values() { $values = array(); foreach ( samcp_safe_setting_keys() as $key ) { $value = get_option( $key ); $values[ $key ] = in_array( $key, array( 'start_of_week', 'posts_per_page', 'page_on_front', 'page_for_posts' ), true ) ? absint( $value ) : (string) $value; } return $values; }
function samcp_settings_hash( $values ) { return hash( 'sha256', (string) wp_json_encode( $values ) ); }
function samcp_format_settings( $snapshot_id = '' ) { $values = samcp_setting_values(); $values['settings_sha256'] = samcp_settings_hash( $values ); $values['snapshot_id'] = (string) $snapshot_id; return $values; }
function samcp_get_site_settings() { return samcp_format_settings(); }
function samcp_save_settings_snapshot( $reason ) { $id = function_exists( 'wp_generate_uuid4' ) ? wp_generate_uuid4() : uniqid( 'settings-', true ); $items = get_option( 'samcp_settings_snapshots', array() ); array_unshift( $items, array( 'id' => $id, 'created_gmt' => gmdate( 'Y-m-d H:i:s' ), 'user_id' => get_current_user_id(), 'reason' => $reason, 'values' => samcp_setting_values() ) ); update_option( 'samcp_settings_snapshots', array_slice( $items, 0, 20 ), false ); return $id; }
function samcp_validate_setting_value( $key, $value ) { if ( in_array( $key, array( 'page_on_front', 'page_for_posts' ), true ) ) { $id = absint( $value ); if ( $id && 'page' !== get_post_type( $id ) ) { return new WP_Error( 'samcp_setting_page_invalid', __( 'Homepage and posts page IDs must refer to WordPress pages.', 'site-abilities-mcp' ) ); } return $id; } if ( 'show_on_front' === $key ) { return in_array( $value, array( 'posts', 'page' ), true ) ? $value : new WP_Error( 'samcp_setting_invalid', __( 'show_on_front must be posts or page.', 'site-abilities-mcp' ) ); } if ( 'start_of_week' === $key ) { $value = absint( $value ); return $value <= 6 ? $value : new WP_Error( 'samcp_setting_invalid', __( 'start_of_week must be from 0 to 6.', 'site-abilities-mcp' ) ); } if ( 'posts_per_page' === $key ) { $value = absint( $value ); return $value >= 1 && $value <= 100 ? $value : new WP_Error( 'samcp_setting_invalid', __( 'posts_per_page must be from 1 to 100.', 'site-abilities-mcp' ) ); } if ( 'timezone_string' === $key ) { $value = sanitize_text_field( $value ); return in_array( $value, timezone_identifiers_list(), true ) || '' === $value ? $value : new WP_Error( 'samcp_setting_invalid', __( 'timezone_string must be a valid PHP timezone identifier.', 'site-abilities-mcp' ) ); } return sanitize_text_field( $value ); }
function samcp_validate_settings_combination( $changes ) { $combined = array_merge( samcp_setting_values(), $changes ); if ( ! empty( $combined['page_on_front'] ) && absint( $combined['page_on_front'] ) === absint( $combined['page_for_posts'] ) ) { return new WP_Error( 'samcp_setting_pages_conflict', __( 'The static homepage and posts page must be different pages.', 'site-abilities-mcp' ) ); } if ( 'page' === $combined['show_on_front'] && empty( $combined['page_on_front'] ) ) { return new WP_Error( 'samcp_setting_homepage_required', __( 'A valid homepage page ID is required when show_on_front is set to page.', 'site-abilities-mcp' ) ); } return true; }
function samcp_write_settings( $values ) { foreach ( array_intersect_key( $values, array_flip( samcp_safe_setting_keys() ) ) as $key => $value ) { $value = samcp_validate_setting_value( $key, $value ); if ( is_wp_error( $value ) ) { return $value; } update_option( $key, $value ); } return true; }
function samcp_update_site_settings( $input ) { if ( empty( $input['confirmation'] ) || 'UPDATE_SITE_SETTINGS' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit UPDATE_SITE_SETTINGS confirmation is required.', 'site-abilities-mcp' ) ); } $current = samcp_setting_values(); if ( ! hash_equals( samcp_settings_hash( $current ), strtolower( (string) $input['expected_settings_sha256'] ) ) ) { return new WP_Error( 'samcp_settings_changed', __( 'Site settings changed after they were read. Read them again before retrying.', 'site-abilities-mcp' ) ); } $changes = array_intersect_key( $input, array_flip( samcp_safe_setting_keys() ) ); if ( ! $changes ) { return new WP_Error( 'samcp_no_changes', __( 'No allowlisted setting changes were supplied.', 'site-abilities-mcp' ) ); } foreach ( $changes as $key => $value ) { $validated = samcp_validate_setting_value( $key, $value ); if ( is_wp_error( $validated ) ) { return $validated; } $changes[ $key ] = $validated; } $combination = samcp_validate_settings_combination( $changes ); if ( is_wp_error( $combination ) ) { return $combination; } $snapshot = samcp_save_settings_snapshot( 'before_update' ); $result = samcp_write_settings( $changes ); return is_wp_error( $result ) ? $result : samcp_format_settings( $snapshot ); }
function samcp_restore_site_settings( $input ) { if ( empty( $input['confirmation'] ) || 'RESTORE_SITE_SETTINGS' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit RESTORE_SITE_SETTINGS confirmation is required.', 'site-abilities-mcp' ) ); } $current = samcp_setting_values(); if ( ! hash_equals( samcp_settings_hash( $current ), strtolower( (string) $input['expected_settings_sha256'] ) ) ) { return new WP_Error( 'samcp_settings_changed', __( 'Site settings changed after they were read. Read them again before retrying.', 'site-abilities-mcp' ) ); } $snapshot = null; foreach ( get_option( 'samcp_settings_snapshots', array() ) as $candidate ) { if ( hash_equals( (string) $candidate['id'], (string) $input['snapshot_id'] ) ) { $snapshot = $candidate; break; } } if ( ! $snapshot ) { return new WP_Error( 'samcp_settings_snapshot_not_found', __( 'The requested settings snapshot was not found.', 'site-abilities-mcp' ) ); } samcp_save_settings_snapshot( 'before_restore' ); $result = samcp_write_settings( $snapshot['values'] ); return is_wp_error( $result ) ? $result : samcp_format_settings(); }
function samcp_plugin_inventory() { require_once ABSPATH . 'wp-admin/includes/plugin.php'; $active = (array) get_option( 'active_plugins', array() ); $items = array(); foreach ( get_plugins() as $file => $data ) { $items[] = array( 'plugin_file' => $file, 'name' => (string) $data['Name'], 'version' => (string) $data['Version'], 'active' => in_array( $file, $active, true ) || is_plugin_active_for_network( $file ), 'network_active' => is_plugin_active_for_network( $file ), 'protected' => samcp_plugin_is_protected( $file ) ); } usort( $items, static function ( $a, $b ) { return strcasecmp( $a['name'], $b['name'] ); } ); return $items; }
function samcp_plugin_inventory_hash( $items ) { return hash( 'sha256', (string) wp_json_encode( $items ) ); }
function samcp_plugin_is_protected( $file ) { $protected = array( 'mcp-adapter', 'site-abilities-mcp', 'woocommerce/woocommerce.php', 'js_composer' ); if ( function_exists( 'apply_filters' ) ) { $protected = (array) apply_filters( 'site_abilities_mcp_protected_plugins', $protected ); } foreach ( $protected as $needle ) { if ( is_string( $needle ) && '' !== $needle && false !== stripos( $file, $needle ) ) { return true; } } return false; }
function samcp_list_plugins() { $items = samcp_plugin_inventory(); return array( 'plugins_sha256' => samcp_plugin_inventory_hash( $items ), 'plugins' => $items ); }
function samcp_set_plugin_state( $input ) { if ( empty( $input['confirmation'] ) || 'SET_PLUGIN_STATE' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit SET_PLUGIN_STATE confirmation is required.', 'site-abilities-mcp' ) ); } $inventory = samcp_plugin_inventory(); if ( ! hash_equals( samcp_plugin_inventory_hash( $inventory ), strtolower( (string) $input['expected_plugins_sha256'] ) ) ) { return new WP_Error( 'samcp_plugins_changed', __( 'Plugin state changed after it was read. List plugins again before retrying.', 'site-abilities-mcp' ) ); } $file = plugin_basename( sanitize_text_field( $input['plugin_file'] ) ); $known = false; foreach ( $inventory as $plugin ) { if ( $plugin['plugin_file'] === $file ) { $known = true; break; } } if ( ! $known ) { return new WP_Error( 'samcp_plugin_not_found', __( 'The requested installed plugin was not found.', 'site-abilities-mcp' ) ); } if ( samcp_plugin_is_protected( $file ) ) { return new WP_Error( 'samcp_plugin_protected', __( 'This plugin is protected because changing it could break MCP, commerce or the active site design.', 'site-abilities-mcp' ) ); } require_once ABSPATH . 'wp-admin/includes/plugin.php'; if ( 'active' === $input['state'] ) { $result = activate_plugin( $file, '', false, false ); if ( is_wp_error( $result ) ) { return $result; } } else { deactivate_plugins( $file, false, false ); } $items = samcp_plugin_inventory(); return array( 'plugin_file' => $file, 'state' => is_plugin_active( $file ) ? 'active' : 'inactive', 'plugins_sha256' => samcp_plugin_inventory_hash( $items ) ); }
function samcp_list_themes() { $active = get_stylesheet(); $items = array(); foreach ( wp_get_themes() as $stylesheet => $theme ) { $items[] = array( 'stylesheet' => (string) $stylesheet, 'name' => (string) $theme->get( 'Name' ), 'version' => (string) $theme->get( 'Version' ), 'active' => $stylesheet === $active, 'parent' => (string) $theme->get( 'Template' ) ); } return $items; }
