<?php
/** Recoverable classic-menu management abilities. */

if ( ! defined( 'ABSPATH' ) ) { exit; }

function samcp_register_menu_category() {
	if ( function_exists( 'wp_register_ability_category' ) ) { wp_register_ability_category( 'site-abilities-menus', array( 'label' => __( 'Site Menus', 'site-abilities-mcp' ), 'description' => __( 'Classic menu management with bounded snapshots.', 'site-abilities-mcp' ) ) ); }
}
add_action( 'wp_abilities_api_categories_init', 'samcp_register_menu_category' );

function samcp_menu_schema() {
	return array( 'type' => 'object', 'required' => array( 'id', 'name', 'slug', 'item_count', 'menu_sha256' ), 'properties' => array( 'id' => array( 'type' => 'integer' ), 'name' => array( 'type' => 'string' ), 'slug' => array( 'type' => 'string' ), 'locations' => array( 'type' => 'array', 'items' => array( 'type' => 'string' ) ), 'item_count' => array( 'type' => 'integer' ), 'items' => array( 'type' => 'array', 'items' => array( 'type' => 'object' ) ), 'menu_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ) ) );
}
function samcp_menu_input_schema( $item = false, $confirmation = '' ) {
	$schema = array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'menu_id', 'expected_menu_sha256' ), 'properties' => array( 'menu_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'expected_menu_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ) ) );
	if ( $item ) { $schema['required'][] = 'menu_item_id'; $schema['properties']['menu_item_id'] = array( 'type' => 'integer', 'minimum' => 1 ); }
	if ( $confirmation ) { $schema['required'][] = 'confirmation'; $schema['properties']['confirmation'] = array( 'type' => 'string', 'enum' => array( $confirmation ) ); }
	return $schema;
}
function samcp_register_menu_abilities() {
	if ( ! function_exists( 'wp_register_ability' ) ) { return; }
	wp_register_ability( 'site-abilities/list-menus', array( 'label' => __( 'List classic menus', 'site-abilities-mcp' ), 'description' => __( 'Lists classic WordPress menus and assigned theme locations.', 'site-abilities-mcp' ), 'category' => 'site-abilities-menus', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false ), 'output_schema' => array( 'type' => 'array', 'items' => samcp_menu_schema() ), 'execute_callback' => 'samcp_list_menus', 'permission_callback' => 'samcp_can_manage_menus', 'meta' => samcp_ability_meta( true, false, true ) ) );
	wp_register_ability( 'site-abilities/get-menu', array( 'label' => __( 'Read a classic menu', 'site-abilities-mcp' ), 'description' => __( 'Reads a menu hierarchy and returns a checksum for guarded changes.', 'site-abilities-mcp' ), 'category' => 'site-abilities-menus', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'menu_id' ), 'properties' => array( 'menu_id' => array( 'type' => 'integer', 'minimum' => 1 ) ) ), 'output_schema' => samcp_menu_schema(), 'execute_callback' => 'samcp_get_menu', 'permission_callback' => 'samcp_can_manage_menus', 'meta' => samcp_ability_meta( true, false, true ) ) );

	$add = samcp_menu_input_schema( false, 'ADD_MENU_ITEM' );
	$add['required'][] = 'title'; $add['required'][] = 'item_type';
	$add['properties'] += array( 'title' => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 500 ), 'item_type' => array( 'type' => 'string', 'enum' => array( 'custom', 'post_type' ) ), 'url' => array( 'type' => 'string', 'maxLength' => 2000 ), 'object_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'parent_item_id' => array( 'type' => 'integer', 'minimum' => 0, 'default' => 0 ), 'position' => array( 'type' => 'integer', 'minimum' => 1, 'default' => 1 ), 'open_in_new_tab' => array( 'type' => 'boolean', 'default' => false ) );
	wp_register_ability( 'site-abilities/add-menu-item', array( 'label' => __( 'Add classic menu item', 'site-abilities-mcp' ), 'description' => __( 'Adds a custom link or allowed content link after a menu checksum check and automatic snapshot.', 'site-abilities-mcp' ), 'category' => 'site-abilities-menus', 'input_schema' => $add, 'output_schema' => array( 'type' => 'object', 'properties' => array( 'snapshot_id' => array( 'type' => 'string' ), 'menu' => samcp_menu_schema() ) ), 'execute_callback' => 'samcp_add_menu_item', 'permission_callback' => 'samcp_can_manage_menus', 'meta' => samcp_ability_meta( false, true, false ) ) );

	$update = samcp_menu_input_schema( true, 'UPDATE_MENU_ITEM' );
	$update['properties'] += array( 'title' => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 500 ), 'url' => array( 'type' => 'string', 'maxLength' => 2000 ), 'parent_item_id' => array( 'type' => 'integer', 'minimum' => 0 ), 'position' => array( 'type' => 'integer', 'minimum' => 1 ), 'open_in_new_tab' => array( 'type' => 'boolean' ) );
	wp_register_ability( 'site-abilities/update-menu-item', array( 'label' => __( 'Update classic menu item', 'site-abilities-mcp' ), 'description' => __( 'Updates label, URL, parent, position or target after an automatic menu snapshot.', 'site-abilities-mcp' ), 'category' => 'site-abilities-menus', 'input_schema' => $update, 'output_schema' => array( 'type' => 'object', 'properties' => array( 'snapshot_id' => array( 'type' => 'string' ), 'menu' => samcp_menu_schema() ) ), 'execute_callback' => 'samcp_update_menu_item', 'permission_callback' => 'samcp_can_manage_menus', 'meta' => samcp_ability_meta( false, true, false ) ) );
	wp_register_ability( 'site-abilities/remove-menu-item', array( 'label' => __( 'Remove classic menu item', 'site-abilities-mcp' ), 'description' => __( 'Removes one menu item only after an automatic full-menu snapshot and explicit confirmation.', 'site-abilities-mcp' ), 'category' => 'site-abilities-menus', 'input_schema' => samcp_menu_input_schema( true, 'REMOVE_MENU_ITEM' ), 'output_schema' => array( 'type' => 'object', 'properties' => array( 'snapshot_id' => array( 'type' => 'string' ), 'menu' => samcp_menu_schema() ) ), 'execute_callback' => 'samcp_remove_menu_item', 'permission_callback' => 'samcp_can_manage_menus', 'meta' => samcp_ability_meta( false, true, false ) ) );
	wp_register_ability( 'site-abilities/list-menu-snapshots', array( 'label' => __( 'List menu snapshots', 'site-abilities-mcp' ), 'description' => __( 'Lists the most recent recoverable menu snapshots.', 'site-abilities-mcp' ), 'category' => 'site-abilities-menus', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'properties' => array( 'menu_id' => array( 'type' => 'integer', 'minimum' => 1 ) ) ), 'output_schema' => array( 'type' => 'array', 'items' => array( 'type' => 'object' ) ), 'execute_callback' => 'samcp_list_menu_snapshots', 'permission_callback' => 'samcp_can_manage_menus', 'meta' => samcp_ability_meta( true, false, true ) ) );
	wp_register_ability( 'site-abilities/restore-menu-snapshot', array( 'label' => __( 'Restore menu snapshot', 'site-abilities-mcp' ), 'description' => __( 'Restores a complete classic menu snapshot after current-state validation and explicit confirmation.', 'site-abilities-mcp' ), 'category' => 'site-abilities-menus', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'snapshot_id', 'expected_menu_sha256', 'confirmation' ), 'properties' => array( 'snapshot_id' => array( 'type' => 'string', 'pattern' => '^[a-zA-Z0-9-]{8,64}$' ), 'expected_menu_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'confirmation' => array( 'type' => 'string', 'enum' => array( 'RESTORE_MENU_SNAPSHOT' ) ) ) ), 'output_schema' => samcp_menu_schema(), 'execute_callback' => 'samcp_restore_menu_snapshot', 'permission_callback' => 'samcp_can_manage_menus', 'meta' => samcp_ability_meta( false, true, false ) ) );
}
add_action( 'wp_abilities_api_init', 'samcp_register_menu_abilities' );

function samcp_can_manage_menus() { return current_user_can( 'edit_theme_options' ); }
function samcp_menu_locations_for( $menu_id ) { $result = array(); foreach ( get_nav_menu_locations() as $location => $id ) { if ( absint( $id ) === absint( $menu_id ) ) { $result[] = (string) $location; } } return $result; }
function samcp_menu_items( $menu_id ) {
	$items = wp_get_nav_menu_items( $menu_id, array( 'post_status' => 'any' ) ); if ( ! is_array( $items ) ) { return array(); }
	return array_map( static function ( $item ) { return array( 'id' => (int) $item->ID, 'title' => (string) $item->title, 'url' => (string) $item->url, 'type' => (string) $item->type, 'object' => (string) $item->object, 'object_id' => (int) $item->object_id, 'parent_item_id' => (int) $item->menu_item_parent, 'position' => (int) $item->menu_order, 'target' => (string) $item->target, 'attr_title' => (string) $item->attr_title, 'description' => (string) $item->description, 'xfn' => (string) $item->xfn, 'classes' => array_values( array_filter( (array) $item->classes ) ) ); }, $items );
}
function samcp_menu_hash( $menu_id ) { return hash( 'sha256', (string) wp_json_encode( samcp_menu_items( $menu_id ) ) ); }
function samcp_format_menu( $term, $with_items = true ) { $items = samcp_menu_items( $term->term_id ); $result = array( 'id' => (int) $term->term_id, 'name' => (string) $term->name, 'slug' => (string) $term->slug, 'locations' => samcp_menu_locations_for( $term->term_id ), 'item_count' => count( $items ), 'menu_sha256' => hash( 'sha256', (string) wp_json_encode( $items ) ) ); if ( $with_items ) { $result['items'] = $items; } return $result; }
function samcp_find_menu( $id ) { $term = wp_get_nav_menu_object( absint( $id ) ); return $term ? $term : new WP_Error( 'samcp_menu_not_found', __( 'The requested classic menu was not found.', 'site-abilities-mcp' ) ); }
function samcp_validate_menu_snapshot( $menu_id, $expected ) { $current = samcp_menu_hash( $menu_id ); return hash_equals( $current, strtolower( (string) $expected ) ) ? true : new WP_Error( 'samcp_menu_changed', __( 'The menu changed after it was read. Read it again before retrying.', 'site-abilities-mcp' ), array( 'current_menu_sha256' => $current ) ); }
function samcp_list_menus() { return array_map( static function ( $term ) { return samcp_format_menu( $term, false ); }, wp_get_nav_menus() ); }
function samcp_get_menu( $input ) { $term = samcp_find_menu( $input['menu_id'] ); return is_wp_error( $term ) ? $term : samcp_format_menu( $term ); }
function samcp_save_menu_snapshot( $menu_id, $reason ) {
	$term = samcp_find_menu( $menu_id ); if ( is_wp_error( $term ) ) { return $term; }
	$id = function_exists( 'wp_generate_uuid4' ) ? wp_generate_uuid4() : uniqid( 'menu-', true );
	$snapshots = get_option( 'samcp_menu_snapshots', array() );
	array_unshift( $snapshots, array( 'id' => $id, 'menu_id' => (int) $menu_id, 'menu_name' => (string) $term->name, 'created_gmt' => gmdate( 'Y-m-d H:i:s' ), 'user_id' => get_current_user_id(), 'reason' => $reason, 'items' => samcp_menu_items( $menu_id ) ) );
	$snapshots = array_slice( $snapshots, 0, 20 ); update_option( 'samcp_menu_snapshots', $snapshots, false ); return $id;
}
function samcp_valid_menu_url( $url ) { if ( 0 === strpos( $url, '/' ) && 0 !== strpos( $url, '//' ) ) { return $url; } $url = esc_url_raw( $url, array( 'http', 'https' ) ); return $url ? $url : new WP_Error( 'samcp_menu_url_invalid', __( 'Menu URLs must be relative site paths or valid HTTP(S) URLs.', 'site-abilities-mcp' ) ); }
function samcp_menu_parent_is_valid( $menu_id, $parent_id, $item_id = 0 ) { $parent_id = absint( $parent_id ); if ( 0 === $parent_id ) { return true; } if ( $parent_id === absint( $item_id ) ) { return false; } $parent = get_post( $parent_id ); return $parent && 'nav_menu_item' === $parent->post_type && true === is_object_in_term( $parent_id, 'nav_menu', absint( $menu_id ) ); }
function samcp_menu_item_args( $item ) { return array( 'menu-item-title' => (string) $item->title, 'menu-item-url' => (string) $item->url, 'menu-item-type' => (string) $item->type, 'menu-item-object' => (string) $item->object, 'menu-item-object-id' => (int) $item->object_id, 'menu-item-parent-id' => (int) $item->menu_item_parent, 'menu-item-position' => (int) $item->menu_order, 'menu-item-target' => (string) $item->target, 'menu-item-attr-title' => (string) $item->attr_title, 'menu-item-description' => (string) $item->description, 'menu-item-xfn' => (string) $item->xfn, 'menu-item-classes' => implode( ' ', array_filter( (array) $item->classes ) ), 'menu-item-status' => 'publish' ); }
function samcp_snapshot_menu_item_args( $item ) { return array( 'menu-item-title' => $item['title'], 'menu-item-url' => $item['url'], 'menu-item-type' => $item['type'], 'menu-item-object' => $item['object'], 'menu-item-object-id' => $item['object_id'], 'menu-item-parent-id' => $item['parent_item_id'], 'menu-item-position' => $item['position'], 'menu-item-target' => $item['target'], 'menu-item-attr-title' => isset( $item['attr_title'] ) ? $item['attr_title'] : '', 'menu-item-description' => isset( $item['description'] ) ? $item['description'] : '', 'menu-item-xfn' => isset( $item['xfn'] ) ? $item['xfn'] : '', 'menu-item-classes' => implode( ' ', $item['classes'] ), 'menu-item-status' => 'publish' ); }
function samcp_menu_result( $menu_id, $snapshot_id ) { return array( 'snapshot_id' => (string) $snapshot_id, 'menu' => samcp_format_menu( wp_get_nav_menu_object( $menu_id ) ) ); }
function samcp_add_menu_item( $input ) {
	$check = samcp_validate_menu_snapshot( $input['menu_id'], $input['expected_menu_sha256'] ); if ( is_wp_error( $check ) ) { return $check; }
	if ( empty( $input['confirmation'] ) || 'ADD_MENU_ITEM' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit ADD_MENU_ITEM confirmation is required.', 'site-abilities-mcp' ) ); }
	if ( ! samcp_menu_parent_is_valid( $input['menu_id'], isset( $input['parent_item_id'] ) ? $input['parent_item_id'] : 0 ) ) { return new WP_Error( 'samcp_menu_parent_invalid', __( 'The parent item must belong to the same menu.', 'site-abilities-mcp' ) ); }
	$args = array( 'menu-item-title' => sanitize_text_field( $input['title'] ), 'menu-item-status' => 'publish', 'menu-item-parent-id' => isset( $input['parent_item_id'] ) ? absint( $input['parent_item_id'] ) : 0, 'menu-item-position' => isset( $input['position'] ) ? absint( $input['position'] ) : 1, 'menu-item-target' => ! empty( $input['open_in_new_tab'] ) ? '_blank' : '' );
	if ( 'custom' === $input['item_type'] ) { if ( empty( $input['url'] ) ) { return new WP_Error( 'samcp_menu_url_required', __( 'A URL is required for a custom menu item.', 'site-abilities-mcp' ) ); } $url = samcp_valid_menu_url( $input['url'] ); if ( is_wp_error( $url ) ) { return $url; } $args += array( 'menu-item-type' => 'custom', 'menu-item-url' => $url ); }
	else { $post = ! empty( $input['object_id'] ) ? get_post( absint( $input['object_id'] ) ) : null; $allowed = array_merge( array( 'page', 'product' ), samcp_allowed_content_types() ); if ( ! $post || ! in_array( $post->post_type, $allowed, true ) ) { return new WP_Error( 'samcp_menu_object_invalid', __( 'The linked content item is not an allowed type.', 'site-abilities-mcp' ) ); } $args += array( 'menu-item-type' => 'post_type', 'menu-item-object' => $post->post_type, 'menu-item-object-id' => $post->ID ); }
	$snapshot = samcp_save_menu_snapshot( $input['menu_id'], 'before_add' ); if ( is_wp_error( $snapshot ) ) { return $snapshot; }
	$id = wp_update_nav_menu_item( $input['menu_id'], 0, wp_slash( $args ) ); return is_wp_error( $id ) ? $id : samcp_menu_result( $input['menu_id'], $snapshot );
}
function samcp_update_menu_item( $input ) {
	$check = samcp_validate_menu_snapshot( $input['menu_id'], $input['expected_menu_sha256'] ); if ( is_wp_error( $check ) ) { return $check; }
	if ( empty( $input['confirmation'] ) || 'UPDATE_MENU_ITEM' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit UPDATE_MENU_ITEM confirmation is required.', 'site-abilities-mcp' ) ); }
	$item = get_post( absint( $input['menu_item_id'] ) ); if ( ! $item || 'nav_menu_item' !== $item->post_type || true !== is_object_in_term( $item->ID, 'nav_menu', absint( $input['menu_id'] ) ) ) { return new WP_Error( 'samcp_menu_item_not_found', __( 'The menu item does not belong to this menu.', 'site-abilities-mcp' ) ); }
	if ( array_key_exists( 'parent_item_id', $input ) && ! samcp_menu_parent_is_valid( $input['menu_id'], $input['parent_item_id'], $item->ID ) ) { return new WP_Error( 'samcp_menu_parent_invalid', __( 'The parent item must belong to the same menu and cannot be the item itself.', 'site-abilities-mcp' ) ); }
	$args = samcp_menu_item_args( wp_setup_nav_menu_item( $item ) );
	if ( array_key_exists( 'title', $input ) ) { $args['menu-item-title'] = sanitize_text_field( $input['title'] ); }
	if ( array_key_exists( 'url', $input ) ) { $url = samcp_valid_menu_url( $input['url'] ); if ( is_wp_error( $url ) ) { return $url; } $args['menu-item-url'] = $url; }
	if ( array_key_exists( 'parent_item_id', $input ) ) { $args['menu-item-parent-id'] = absint( $input['parent_item_id'] ); }
	if ( array_key_exists( 'position', $input ) ) { $args['menu-item-position'] = absint( $input['position'] ); }
	if ( array_key_exists( 'open_in_new_tab', $input ) ) { $args['menu-item-target'] = $input['open_in_new_tab'] ? '_blank' : ''; }
	if ( ! array_intersect( array( 'title', 'url', 'parent_item_id', 'position', 'open_in_new_tab' ), array_keys( $input ) ) ) { return new WP_Error( 'samcp_no_changes', __( 'No menu item changes were supplied.', 'site-abilities-mcp' ) ); }
	$snapshot = samcp_save_menu_snapshot( $input['menu_id'], 'before_update' ); $id = wp_update_nav_menu_item( $input['menu_id'], $item->ID, wp_slash( $args ) ); return is_wp_error( $id ) ? $id : samcp_menu_result( $input['menu_id'], $snapshot );
}
function samcp_remove_menu_item( $input ) {
	$check = samcp_validate_menu_snapshot( $input['menu_id'], $input['expected_menu_sha256'] ); if ( is_wp_error( $check ) ) { return $check; }
	if ( empty( $input['confirmation'] ) || 'REMOVE_MENU_ITEM' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit REMOVE_MENU_ITEM confirmation is required.', 'site-abilities-mcp' ) ); }
	$item = get_post( absint( $input['menu_item_id'] ) ); if ( ! $item || 'nav_menu_item' !== $item->post_type || true !== is_object_in_term( $item->ID, 'nav_menu', absint( $input['menu_id'] ) ) ) { return new WP_Error( 'samcp_menu_item_not_found', __( 'The menu item does not belong to this menu.', 'site-abilities-mcp' ) ); }
	$snapshot = samcp_save_menu_snapshot( $input['menu_id'], 'before_remove' ); $result = wp_delete_post( $item->ID, true ); return $result ? samcp_menu_result( $input['menu_id'], $snapshot ) : new WP_Error( 'samcp_menu_remove_failed', __( 'WordPress could not remove the menu item.', 'site-abilities-mcp' ) );
}
function samcp_list_menu_snapshots( $input ) { $items = get_option( 'samcp_menu_snapshots', array() ); if ( ! empty( $input['menu_id'] ) ) { $items = array_filter( $items, static function ( $item ) use ( $input ) { return absint( $item['menu_id'] ) === absint( $input['menu_id'] ); } ); } return array_values( array_map( static function ( $item ) { unset( $item['items'] ); return $item; }, $items ) ); }
function samcp_restore_menu_snapshot( $input ) {
	if ( empty( $input['confirmation'] ) || 'RESTORE_MENU_SNAPSHOT' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit RESTORE_MENU_SNAPSHOT confirmation is required.', 'site-abilities-mcp' ) ); }
	$snapshot = null; foreach ( get_option( 'samcp_menu_snapshots', array() ) as $candidate ) { if ( hash_equals( (string) $candidate['id'], (string) $input['snapshot_id'] ) ) { $snapshot = $candidate; break; } }
	if ( ! $snapshot ) { return new WP_Error( 'samcp_menu_snapshot_not_found', __( 'The requested menu snapshot was not found.', 'site-abilities-mcp' ) ); }
	$check = samcp_validate_menu_snapshot( $snapshot['menu_id'], $input['expected_menu_sha256'] ); if ( is_wp_error( $check ) ) { return $check; }
	samcp_save_menu_snapshot( $snapshot['menu_id'], 'before_restore' ); foreach ( (array) wp_get_nav_menu_items( $snapshot['menu_id'], array( 'post_status' => 'any' ) ) as $item ) { wp_delete_post( $item->ID, true ); }
	$id_map = array(); foreach ( $snapshot['items'] as $item ) { $args = samcp_snapshot_menu_item_args( $item ); $args['menu-item-parent-id'] = 0; $new_id = wp_update_nav_menu_item( $snapshot['menu_id'], 0, wp_slash( $args ) ); if ( is_wp_error( $new_id ) ) { return $new_id; } $id_map[ $item['id'] ] = $new_id; }
	foreach ( $snapshot['items'] as $item ) { $old_parent = absint( $item['parent_item_id'] ); if ( ! $old_parent || ! isset( $id_map[ $old_parent ] ) ) { continue; } $args = samcp_snapshot_menu_item_args( $item ); $args['menu-item-parent-id'] = $id_map[ $old_parent ]; $updated = wp_update_nav_menu_item( $snapshot['menu_id'], $id_map[ $item['id'] ], wp_slash( $args ) ); if ( is_wp_error( $updated ) ) { return $updated; } }
	return samcp_format_menu( wp_get_nav_menu_object( $snapshot['menu_id'] ) );
}
