<?php
/** Controlled WooCommerce simple-product abilities. */

if ( ! defined( 'ABSPATH' ) ) { exit; }

function samcp_register_product_category() { if ( function_exists( 'wp_register_ability_category' ) ) { wp_register_ability_category( 'site-abilities-products', array( 'label' => __( 'Site Products', 'site-abilities-mcp' ), 'description' => __( 'Simple WooCommerce products with snapshots and explicit publication.', 'site-abilities-mcp' ) ) ); } }
add_action( 'wp_abilities_api_categories_init', 'samcp_register_product_category' );

function samcp_product_schema() { return array( 'type' => 'object', 'required' => array( 'id', 'status', 'name', 'description', 'short_description', 'sku', 'regular_price', 'sale_price', 'manage_stock', 'stock_quantity', 'stock_status', 'featured_image_id', 'modified_gmt', 'product_sha256' ), 'properties' => array( 'id' => array( 'type' => 'integer' ), 'status' => array( 'type' => 'string' ), 'name' => array( 'type' => 'string' ), 'description' => array( 'type' => 'string' ), 'short_description' => array( 'type' => 'string' ), 'sku' => array( 'type' => 'string' ), 'regular_price' => array( 'type' => 'string' ), 'sale_price' => array( 'type' => 'string' ), 'manage_stock' => array( 'type' => 'boolean' ), 'stock_quantity' => array( 'type' => array( 'integer', 'null' ) ), 'stock_status' => array( 'type' => 'string' ), 'featured_image_id' => array( 'type' => 'integer' ), 'modified_gmt' => array( 'type' => 'string' ), 'product_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'snapshot_id' => array( 'type' => 'string' ) ) ); }
function samcp_product_id_schema( $mutation = false, $confirmation = '' ) { $schema = array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'product_id' ), 'properties' => array( 'product_id' => array( 'type' => 'integer', 'minimum' => 1 ) ) ); if ( $mutation ) { $schema['required'][] = 'expected_modified_gmt'; $schema['required'][] = 'expected_product_sha256'; $schema['properties']['expected_modified_gmt'] = samcp_expected_modified_schema(); $schema['properties']['expected_product_sha256'] = array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ); if ( $confirmation ) { $schema['required'][] = 'confirmation'; $schema['properties']['confirmation'] = array( 'type' => 'string', 'enum' => array( $confirmation ) ); } } return $schema; }
function samcp_product_fields_schema() { return array( 'name' => array( 'type' => 'string', 'minLength' => 1, 'maxLength' => 500 ), 'description' => array( 'type' => 'string' ), 'short_description' => array( 'type' => 'string' ), 'sku' => array( 'type' => 'string', 'maxLength' => 100 ), 'regular_price' => array( 'type' => 'string', 'pattern' => '^$|^[0-9]+(?:\\.[0-9]+)?$' ), 'sale_price' => array( 'type' => 'string', 'pattern' => '^$|^[0-9]+(?:\\.[0-9]+)?$' ), 'manage_stock' => array( 'type' => 'boolean' ), 'stock_quantity' => array( 'type' => 'integer', 'minimum' => 0 ), 'stock_status' => array( 'type' => 'string', 'enum' => array( 'instock', 'outofstock', 'onbackorder' ) ), 'featured_image_id' => array( 'type' => 'integer', 'minimum' => 0 ) ); }
function samcp_register_product_abilities() {
	if ( ! function_exists( 'wp_register_ability' ) ) { return; }
	wp_register_ability( 'site-abilities/list-products', array( 'label' => __( 'List products', 'site-abilities-mcp' ), 'description' => __( 'Lists WooCommerce products without changing them.', 'site-abilities-mcp' ), 'category' => 'site-abilities-products', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'properties' => array( 'search' => array( 'type' => 'string' ), 'status' => array( 'type' => 'string', 'enum' => array( 'publish', 'draft', 'pending', 'private', 'trash', 'any' ), 'default' => 'any' ), 'per_page' => array( 'type' => 'integer', 'minimum' => 1, 'maximum' => 100, 'default' => 20 ) ) ), 'output_schema' => array( 'type' => 'array', 'items' => samcp_product_schema() ), 'execute_callback' => 'samcp_list_products', 'permission_callback' => 'samcp_can_list_products', 'meta' => samcp_ability_meta( true, false, true ) ) );
	wp_register_ability( 'site-abilities/get-product', array( 'label' => __( 'Read product', 'site-abilities-mcp' ), 'description' => __( 'Reads one simple WooCommerce product and its guarded checksum.', 'site-abilities-mcp' ), 'category' => 'site-abilities-products', 'input_schema' => samcp_product_id_schema(), 'output_schema' => samcp_product_schema(), 'execute_callback' => 'samcp_get_product', 'permission_callback' => 'samcp_can_read_product', 'meta' => samcp_ability_meta( true, false, true ) ) );
	$create = array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'name' ), 'properties' => samcp_product_fields_schema() );
	wp_register_ability( 'site-abilities/create-product-draft', array( 'label' => __( 'Create simple product draft', 'site-abilities-mcp' ), 'description' => __( 'Creates a simple WooCommerce product as a draft and never publishes it.', 'site-abilities-mcp' ), 'category' => 'site-abilities-products', 'input_schema' => $create, 'output_schema' => samcp_product_schema(), 'execute_callback' => 'samcp_create_product_draft', 'permission_callback' => 'samcp_can_create_products', 'meta' => samcp_ability_meta( false, false, false ) ) );
	$update = samcp_product_id_schema( true, 'UPDATE_PRODUCT' ); $update['properties'] += samcp_product_fields_schema();
	wp_register_ability( 'site-abilities/update-product', array( 'label' => __( 'Update simple product', 'site-abilities-mcp' ), 'description' => __( 'Updates a simple product after exact state validation, explicit confirmation and a recoverable full product snapshot.', 'site-abilities-mcp' ), 'category' => 'site-abilities-products', 'input_schema' => $update, 'output_schema' => samcp_product_schema(), 'execute_callback' => 'samcp_update_product', 'permission_callback' => 'samcp_can_edit_product', 'meta' => samcp_ability_meta( false, true, false ) ) );
	wp_register_ability( 'site-abilities/publish-product-draft', array( 'label' => __( 'Publish simple product draft', 'site-abilities-mcp' ), 'description' => __( 'Publishes a product draft after exact state validation and explicit confirmation.', 'site-abilities-mcp' ), 'category' => 'site-abilities-products', 'input_schema' => samcp_product_id_schema( true, 'PUBLISH_PRODUCT' ), 'output_schema' => samcp_product_schema(), 'execute_callback' => 'samcp_publish_product_draft', 'permission_callback' => 'samcp_can_publish_product', 'meta' => samcp_ability_meta( false, true, false ) ) );
	foreach ( array( 'trash-product' => array( 'TRASH_PRODUCT', 'samcp_trash_product' ), 'restore-trashed-product' => array( 'RESTORE_TRASHED_PRODUCT', 'samcp_restore_trashed_product' ) ) as $name => $config ) { wp_register_ability( 'site-abilities/' . $name, array( 'label' => 'trash-product' === $name ? __( 'Move product to trash', 'site-abilities-mcp' ) : __( 'Restore trashed product', 'site-abilities-mcp' ), 'description' => __( 'Changes product trash status after validation and explicit confirmation. Permanent deletion is unavailable.', 'site-abilities-mcp' ), 'category' => 'site-abilities-products', 'input_schema' => samcp_product_id_schema( true, $config[0] ), 'output_schema' => samcp_product_schema(), 'execute_callback' => $config[1], 'permission_callback' => 'samcp_can_delete_product', 'meta' => samcp_ability_meta( false, true, false ) ) ); }
	wp_register_ability( 'site-abilities/list-product-snapshots', array( 'label' => __( 'List product snapshots', 'site-abilities-mcp' ), 'description' => __( 'Lists recent recoverable product snapshots.', 'site-abilities-mcp' ), 'category' => 'site-abilities-products', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'properties' => array( 'product_id' => array( 'type' => 'integer', 'minimum' => 1 ) ) ), 'output_schema' => array( 'type' => 'array', 'items' => array( 'type' => 'object' ) ), 'execute_callback' => 'samcp_list_product_snapshots', 'permission_callback' => 'samcp_can_list_products', 'meta' => samcp_ability_meta( true, false, true ) ) );
	wp_register_ability( 'site-abilities/restore-product-snapshot', array( 'label' => __( 'Restore product snapshot', 'site-abilities-mcp' ), 'description' => __( 'Restores product fields from a snapshot after current-state validation and explicit confirmation.', 'site-abilities-mcp' ), 'category' => 'site-abilities-products', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'snapshot_id', 'expected_modified_gmt', 'expected_product_sha256', 'confirmation' ), 'properties' => array( 'snapshot_id' => array( 'type' => 'string', 'pattern' => '^[a-zA-Z0-9-]{8,64}$' ), 'expected_modified_gmt' => samcp_expected_modified_schema(), 'expected_product_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'confirmation' => array( 'type' => 'string', 'enum' => array( 'RESTORE_PRODUCT_SNAPSHOT' ) ) ) ), 'output_schema' => samcp_product_schema(), 'execute_callback' => 'samcp_restore_product_snapshot', 'permission_callback' => 'samcp_can_restore_product_snapshot', 'meta' => samcp_ability_meta( false, true, false ) ) );
}
add_action( 'wp_abilities_api_init', 'samcp_register_product_abilities' );

function samcp_woocommerce_ready() { return function_exists( 'wc_get_product' ) && class_exists( 'WC_Product_Simple' ); }
function samcp_can_list_products() { return current_user_can( 'edit_products' ); }
function samcp_can_create_products() { return current_user_can( 'edit_products' ); }
function samcp_can_read_product( $input ) { return ! empty( $input['product_id'] ) && current_user_can( 'read_post', absint( $input['product_id'] ) ); }
function samcp_can_edit_product( $input ) { if ( empty( $input['product_id'] ) || ! current_user_can( 'edit_post', absint( $input['product_id'] ) ) ) { return false; } $post = get_post( absint( $input['product_id'] ) ); return ! $post || 'publish' !== $post->post_status || current_user_can( 'publish_products' ); }
function samcp_can_delete_product( $input ) { return ! empty( $input['product_id'] ) && current_user_can( 'delete_post', absint( $input['product_id'] ) ); }
function samcp_can_publish_product( $input ) { return samcp_can_edit_product( $input ) && current_user_can( 'publish_products' ); }
function samcp_can_restore_product_snapshot( $input ) { foreach ( get_option( 'samcp_product_snapshots', array() ) as $item ) { if ( isset( $input['snapshot_id'] ) && hash_equals( (string) $item['id'], (string) $input['snapshot_id'] ) ) { return current_user_can( 'edit_post', absint( $item['product_id'] ) ) && ( 'publish' !== $item['values']['status'] || current_user_can( 'publish_products' ) ); } } return false; }
function samcp_find_product( $id ) { if ( ! samcp_woocommerce_ready() ) { return new WP_Error( 'samcp_woocommerce_unavailable', __( 'WooCommerce is not active.', 'site-abilities-mcp' ) ); } $product = wc_get_product( absint( $id ) ); if ( ! $product || ! $product->is_type( 'simple' ) ) { return new WP_Error( 'samcp_product_not_simple', __( 'Only existing simple WooCommerce products are supported.', 'site-abilities-mcp' ) ); } return $product; }
function samcp_product_values( $product ) { $post = get_post( $product->get_id() ); return array( 'id' => (int) $product->get_id(), 'status' => (string) $product->get_status(), 'name' => (string) $product->get_name(), 'description' => (string) $product->get_description(), 'short_description' => (string) $product->get_short_description(), 'sku' => (string) $product->get_sku(), 'regular_price' => (string) $product->get_regular_price(), 'sale_price' => (string) $product->get_sale_price(), 'manage_stock' => (bool) $product->get_manage_stock(), 'stock_quantity' => null === $product->get_stock_quantity() ? null : (int) $product->get_stock_quantity(), 'stock_status' => (string) $product->get_stock_status(), 'featured_image_id' => (int) $product->get_image_id(), 'modified_gmt' => (string) $post->post_modified_gmt ); }
function samcp_product_hash( $values ) { $copy = $values; unset( $copy['product_sha256'], $copy['snapshot_id'], $copy['modified_gmt'] ); return hash( 'sha256', (string) wp_json_encode( $copy ) ); }
function samcp_format_product( $product, $snapshot_id = '' ) { $values = samcp_product_values( $product ); $values['product_sha256'] = samcp_product_hash( $values ); $values['snapshot_id'] = (string) $snapshot_id; return $values; }
function samcp_validate_product_snapshot( $product, $input ) { $current = samcp_format_product( $product ); return ( $current['modified_gmt'] === (string) $input['expected_modified_gmt'] && hash_equals( $current['product_sha256'], strtolower( (string) $input['expected_product_sha256'] ) ) ) ? true : new WP_Error( 'samcp_product_changed', __( 'The product changed after it was read. Read it again before retrying.', 'site-abilities-mcp' ), array( 'current_modified_gmt' => $current['modified_gmt'], 'current_product_sha256' => $current['product_sha256'] ) ); }
function samcp_list_products( $input ) { if ( ! samcp_woocommerce_ready() ) { return new WP_Error( 'samcp_woocommerce_unavailable', __( 'WooCommerce is not active.', 'site-abilities-mcp' ) ); } $args = array( 'limit' => isset( $input['per_page'] ) ? min( 100, absint( $input['per_page'] ) ) : 20, 'status' => isset( $input['status'] ) && 'any' !== $input['status'] ? $input['status'] : array( 'publish', 'draft', 'pending', 'private', 'trash' ), 'type' => 'simple', 'orderby' => 'modified', 'order' => 'DESC' ); if ( ! empty( $input['search'] ) ) { $args['name'] = sanitize_text_field( $input['search'] ); } return array_values( array_map( 'samcp_format_product', array_filter( wc_get_products( $args ), static function ( $product ) { return current_user_can( 'read_post', $product->get_id() ); } ) ) ); }
function samcp_get_product( $input ) { $product = samcp_find_product( $input['product_id'] ); return is_wp_error( $product ) ? $product : samcp_format_product( $product ); }
function samcp_apply_product_fields( $product, $input ) { $map = array( 'name' => 'set_name', 'description' => 'set_description', 'short_description' => 'set_short_description', 'sku' => 'set_sku', 'regular_price' => 'set_regular_price', 'sale_price' => 'set_sale_price', 'manage_stock' => 'set_manage_stock', 'stock_quantity' => 'set_stock_quantity', 'stock_status' => 'set_stock_status', 'featured_image_id' => 'set_image_id' ); foreach ( $map as $field => $setter ) { if ( array_key_exists( $field, $input ) ) { $value = $input[ $field ]; if ( in_array( $field, array( 'regular_price', 'sale_price' ), true ) ) { $value = '' === $value ? '' : wc_format_decimal( $value ); } elseif ( in_array( $field, array( 'stock_quantity', 'featured_image_id' ), true ) ) { $value = absint( $value ); } elseif ( 'manage_stock' !== $field ) { $value = (string) $value; } $product->{$setter}( $value ); } } }
function samcp_validate_product_fields( $input ) { if ( ! empty( $input['featured_image_id'] ) && ( 'attachment' !== get_post_type( absint( $input['featured_image_id'] ) ) || ! wp_attachment_is_image( absint( $input['featured_image_id'] ) ) ) ) { return new WP_Error( 'samcp_product_image_invalid', __( 'Featured image ID must identify an image attachment.', 'site-abilities-mcp' ) ); } return true; }
function samcp_create_product_draft( $input ) { if ( ! samcp_woocommerce_ready() ) { return new WP_Error( 'samcp_woocommerce_unavailable', __( 'WooCommerce is not active.', 'site-abilities-mcp' ) ); } $validation = samcp_validate_product_fields( $input ); if ( is_wp_error( $validation ) ) { return $validation; } try { $product = new WC_Product_Simple(); $product->set_status( 'draft' ); samcp_apply_product_fields( $product, $input ); $product->save(); return samcp_format_product( $product ); } catch ( Exception $e ) { return new WP_Error( 'samcp_product_create_failed', $e->getMessage() ); } }
function samcp_save_product_snapshot( $product, $reason ) { $id = function_exists( 'wp_generate_uuid4' ) ? wp_generate_uuid4() : uniqid( 'product-', true ); $items = get_option( 'samcp_product_snapshots', array() ); array_unshift( $items, array( 'id' => $id, 'product_id' => (int) $product->get_id(), 'created_gmt' => gmdate( 'Y-m-d H:i:s' ), 'user_id' => get_current_user_id(), 'reason' => $reason, 'values' => samcp_product_values( $product ) ) ); update_option( 'samcp_product_snapshots', array_slice( $items, 0, 30 ), false ); return $id; }
function samcp_update_product( $input ) { $product = samcp_find_product( $input['product_id'] ); if ( is_wp_error( $product ) ) { return $product; } if ( empty( $input['confirmation'] ) || 'UPDATE_PRODUCT' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit UPDATE_PRODUCT confirmation is required.', 'site-abilities-mcp' ) ); } $check = samcp_validate_product_snapshot( $product, $input ); if ( is_wp_error( $check ) ) { return $check; } $changes = array_intersect_key( $input, samcp_product_fields_schema() ); if ( ! $changes ) { return new WP_Error( 'samcp_no_changes', __( 'No product changes were supplied.', 'site-abilities-mcp' ) ); } $validation = samcp_validate_product_fields( $changes ); if ( is_wp_error( $validation ) ) { return $validation; } $snapshot = samcp_save_product_snapshot( $product, 'before_update' ); try { samcp_apply_product_fields( $product, $changes ); $product->save(); return samcp_format_product( $product, $snapshot ); } catch ( Exception $e ) { return new WP_Error( 'samcp_product_update_failed', $e->getMessage() ); } }
function samcp_publish_product_draft( $input ) { $product = samcp_find_product( $input['product_id'] ); if ( is_wp_error( $product ) ) { return $product; } if ( 'draft' !== $product->get_status() ) { return new WP_Error( 'samcp_product_not_draft', __( 'Only draft products can be published.', 'site-abilities-mcp' ) ); } if ( empty( $input['confirmation'] ) || 'PUBLISH_PRODUCT' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit PUBLISH_PRODUCT confirmation is required.', 'site-abilities-mcp' ) ); } $check = samcp_validate_product_snapshot( $product, $input ); if ( is_wp_error( $check ) ) { return $check; } $snapshot = samcp_save_product_snapshot( $product, 'before_publish' ); try { $product->set_status( 'publish' ); $product->save(); return samcp_format_product( $product, $snapshot ); } catch ( Exception $e ) { return new WP_Error( 'samcp_product_publish_failed', $e->getMessage() ); } }
function samcp_trash_product( $input ) { $product = samcp_find_product( $input['product_id'] ); if ( is_wp_error( $product ) ) { return $product; } if ( empty( $input['confirmation'] ) || 'TRASH_PRODUCT' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit TRASH_PRODUCT confirmation is required.', 'site-abilities-mcp' ) ); } $check = samcp_validate_product_snapshot( $product, $input ); if ( is_wp_error( $check ) ) { return $check; } $result = wp_trash_post( $product->get_id() ); return $result ? samcp_format_product( wc_get_product( $product->get_id() ) ) : new WP_Error( 'samcp_trash_failed', __( 'WordPress could not move the product to trash.', 'site-abilities-mcp' ) ); }
function samcp_restore_trashed_product( $input ) { $product = samcp_find_product( $input['product_id'] ); if ( is_wp_error( $product ) ) { return $product; } if ( 'trash' !== $product->get_status() ) { return new WP_Error( 'samcp_product_not_trashed', __( 'Only trashed products can be restored.', 'site-abilities-mcp' ) ); } if ( empty( $input['confirmation'] ) || 'RESTORE_TRASHED_PRODUCT' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit RESTORE_TRASHED_PRODUCT confirmation is required.', 'site-abilities-mcp' ) ); } $check = samcp_validate_product_snapshot( $product, $input ); if ( is_wp_error( $check ) ) { return $check; } $result = wp_untrash_post( $product->get_id() ); if ( ! $result ) { return new WP_Error( 'samcp_untrash_failed', __( 'WordPress could not restore the product.', 'site-abilities-mcp' ) ); } $restored = wc_get_product( $product->get_id() ); $restored->set_status( 'draft' ); $restored->save(); return samcp_format_product( $restored ); }
function samcp_list_product_snapshots( $input ) { $items = get_option( 'samcp_product_snapshots', array() ); if ( ! empty( $input['product_id'] ) ) { $items = array_filter( $items, static function ( $item ) use ( $input ) { return absint( $item['product_id'] ) === absint( $input['product_id'] ); } ); } return array_values( array_map( static function ( $item ) { unset( $item['values'] ); return $item; }, $items ) ); }
function samcp_restore_product_snapshot( $input ) { if ( empty( $input['confirmation'] ) || 'RESTORE_PRODUCT_SNAPSHOT' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit RESTORE_PRODUCT_SNAPSHOT confirmation is required.', 'site-abilities-mcp' ) ); } $snapshot = null; foreach ( get_option( 'samcp_product_snapshots', array() ) as $candidate ) { if ( hash_equals( (string) $candidate['id'], (string) $input['snapshot_id'] ) ) { $snapshot = $candidate; break; } } if ( ! $snapshot ) { return new WP_Error( 'samcp_product_snapshot_not_found', __( 'The requested product snapshot was not found.', 'site-abilities-mcp' ) ); } $product = samcp_find_product( $snapshot['product_id'] ); if ( is_wp_error( $product ) ) { return $product; } $check = samcp_validate_product_snapshot( $product, $input ); if ( is_wp_error( $check ) ) { return $check; } $validation = samcp_validate_product_fields( $snapshot['values'] ); if ( is_wp_error( $validation ) ) { return $validation; } samcp_save_product_snapshot( $product, 'before_restore' ); $values = $snapshot['values']; $status = $values['status']; unset( $values['id'], $values['status'], $values['modified_gmt'] ); try { samcp_apply_product_fields( $product, $values ); $product->set_status( $status ); $product->save(); return samcp_format_product( $product ); } catch ( Exception $e ) { return new WP_Error( 'samcp_product_restore_failed', $e->getMessage() ); } }
