<?php
/** Native, conflict-aware SEO metadata abilities. */

if ( ! defined( 'ABSPATH' ) ) { exit; }

function samcp_register_seo_category() {
	if ( function_exists( 'wp_register_ability_category' ) ) { wp_register_ability_category( 'site-abilities-seo', array( 'label' => __( 'Site SEO', 'site-abilities-mcp' ), 'description' => __( 'Native SEO metadata with checksums and snapshots.', 'site-abilities-mcp' ) ) ); }
}
add_action( 'wp_abilities_api_categories_init', 'samcp_register_seo_category' );

function samcp_seo_supported_types() { return array_merge( array( 'page', 'product' ), samcp_allowed_content_types() ); }
function samcp_seo_schema() {
	return array( 'type' => 'object', 'required' => array( 'post_id', 'post_type', 'title', 'description', 'canonical', 'og_title', 'og_description', 'og_image_id', 'noindex', 'seo_sha256', 'output_active' ), 'properties' => array( 'post_id' => array( 'type' => 'integer' ), 'post_type' => array( 'type' => 'string' ), 'title' => array( 'type' => 'string' ), 'description' => array( 'type' => 'string' ), 'canonical' => array( 'type' => 'string' ), 'og_title' => array( 'type' => 'string' ), 'og_description' => array( 'type' => 'string' ), 'og_image_id' => array( 'type' => 'integer' ), 'noindex' => array( 'type' => 'boolean' ), 'seo_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'output_active' => array( 'type' => 'boolean' ), 'snapshot_id' => array( 'type' => 'string' ) ) );
}
function samcp_register_seo_abilities() {
	if ( ! function_exists( 'wp_register_ability' ) ) { return; }
	wp_register_ability( 'site-abilities/get-seo', array( 'label' => __( 'Read SEO metadata', 'site-abilities-mcp' ), 'description' => __( 'Reads native Site SEO metadata and reports whether native output is active.', 'site-abilities-mcp' ), 'category' => 'site-abilities-seo', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'post_id' ), 'properties' => array( 'post_id' => array( 'type' => 'integer', 'minimum' => 1 ) ) ), 'output_schema' => samcp_seo_schema(), 'execute_callback' => 'samcp_get_seo', 'permission_callback' => 'samcp_can_read_seo', 'meta' => samcp_ability_meta( true, false, true ) ) );
	wp_register_ability( 'site-abilities/update-seo', array( 'label' => __( 'Update SEO metadata', 'site-abilities-mcp' ), 'description' => __( 'Updates only the native Site SEO fields after checksum validation, explicit confirmation and a recoverable snapshot.', 'site-abilities-mcp' ), 'category' => 'site-abilities-seo', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'post_id', 'expected_seo_sha256', 'confirmation' ), 'properties' => array( 'post_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'expected_seo_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'confirmation' => array( 'type' => 'string', 'enum' => array( 'UPDATE_SEO' ) ), 'title' => array( 'type' => 'string', 'maxLength' => 300 ), 'description' => array( 'type' => 'string', 'maxLength' => 1000 ), 'canonical' => array( 'type' => 'string', 'maxLength' => 2000 ), 'og_title' => array( 'type' => 'string', 'maxLength' => 300 ), 'og_description' => array( 'type' => 'string', 'maxLength' => 1000 ), 'og_image_id' => array( 'type' => 'integer', 'minimum' => 0 ), 'noindex' => array( 'type' => 'boolean' ) ) ), 'output_schema' => samcp_seo_schema(), 'execute_callback' => 'samcp_update_seo', 'permission_callback' => 'samcp_can_edit_seo', 'meta' => samcp_ability_meta( false, true, false ) ) );
	wp_register_ability( 'site-abilities/list-seo-snapshots', array( 'label' => __( 'List SEO snapshots', 'site-abilities-mcp' ), 'description' => __( 'Lists recent recoverable SEO metadata snapshots.', 'site-abilities-mcp' ), 'category' => 'site-abilities-seo', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'properties' => array( 'post_id' => array( 'type' => 'integer', 'minimum' => 1 ) ) ), 'output_schema' => array( 'type' => 'array', 'items' => array( 'type' => 'object' ) ), 'execute_callback' => 'samcp_list_seo_snapshots', 'permission_callback' => 'samcp_can_list_seo_snapshots', 'meta' => samcp_ability_meta( true, false, true ) ) );
	wp_register_ability( 'site-abilities/restore-seo-snapshot', array( 'label' => __( 'Restore SEO snapshot', 'site-abilities-mcp' ), 'description' => __( 'Restores an SEO metadata snapshot after current checksum validation and explicit confirmation.', 'site-abilities-mcp' ), 'category' => 'site-abilities-seo', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'snapshot_id', 'expected_seo_sha256', 'confirmation' ), 'properties' => array( 'snapshot_id' => array( 'type' => 'string', 'pattern' => '^[a-zA-Z0-9-]{8,64}$' ), 'expected_seo_sha256' => array( 'type' => 'string', 'pattern' => '^[a-f0-9]{64}$' ), 'confirmation' => array( 'type' => 'string', 'enum' => array( 'RESTORE_SEO_SNAPSHOT' ) ) ) ), 'output_schema' => samcp_seo_schema(), 'execute_callback' => 'samcp_restore_seo_snapshot', 'permission_callback' => 'samcp_can_restore_seo_snapshot', 'meta' => samcp_ability_meta( false, true, false ) ) );
}
add_action( 'wp_abilities_api_init', 'samcp_register_seo_abilities' );

function samcp_find_seo_post( $id ) { $post = get_post( absint( $id ) ); return $post && in_array( $post->post_type, samcp_seo_supported_types(), true ) ? $post : new WP_Error( 'samcp_seo_post_not_found', __( 'The requested SEO-supported content item was not found.', 'site-abilities-mcp' ) ); }
function samcp_can_read_seo( $input ) { return ! empty( $input['post_id'] ) && current_user_can( 'read_post', absint( $input['post_id'] ) ); }
function samcp_can_edit_seo( $input ) { return ! empty( $input['post_id'] ) && current_user_can( 'edit_post', absint( $input['post_id'] ) ); }
function samcp_can_list_seo_snapshots() { return current_user_can( 'edit_posts' ) || current_user_can( 'edit_pages' ); }
function samcp_can_restore_seo_snapshot( $input ) { foreach ( get_option( 'samcp_seo_snapshots', array() ) as $item ) { if ( isset( $input['snapshot_id'] ) && hash_equals( (string) $item['id'], (string) $input['snapshot_id'] ) ) { return current_user_can( 'edit_post', absint( $item['post_id'] ) ); } } return false; }
function samcp_seo_keys() { return array( 'title' => '_samcp_seo_title', 'description' => '_samcp_seo_description', 'canonical' => '_samcp_seo_canonical', 'og_title' => '_samcp_seo_og_title', 'og_description' => '_samcp_seo_og_description', 'og_image_id' => '_samcp_seo_og_image_id', 'noindex' => '_samcp_seo_noindex' ); }
function samcp_seo_values( $post_id ) { $values = array(); foreach ( samcp_seo_keys() as $field => $key ) { $value = get_post_meta( $post_id, $key, true ); $values[ $field ] = 'og_image_id' === $field ? absint( $value ) : ( 'noindex' === $field ? (bool) $value : (string) $value ); } return $values; }
function samcp_seo_hash( $values ) { return hash( 'sha256', (string) wp_json_encode( $values ) ); }
function samcp_standard_seo_active() { return defined( 'WPSEO_VERSION' ) || defined( 'RANK_MATH_VERSION' ) || defined( 'AIOSEO_VERSION' ) || class_exists( 'All_in_One_SEO_Pack' ); }
function samcp_format_seo( $post_id, $snapshot_id = '' ) { $post = get_post( $post_id ); $values = samcp_seo_values( $post_id ); return array_merge( array( 'post_id' => (int) $post_id, 'post_type' => (string) $post->post_type ), $values, array( 'seo_sha256' => samcp_seo_hash( $values ), 'output_active' => ! samcp_standard_seo_active(), 'snapshot_id' => (string) $snapshot_id ) ); }
function samcp_get_seo( $input ) { $post = samcp_find_seo_post( $input['post_id'] ); return is_wp_error( $post ) ? $post : samcp_format_seo( $post->ID ); }
function samcp_save_seo_snapshot( $post_id, $reason ) { $id = function_exists( 'wp_generate_uuid4' ) ? wp_generate_uuid4() : uniqid( 'seo-', true ); $items = get_option( 'samcp_seo_snapshots', array() ); array_unshift( $items, array( 'id' => $id, 'post_id' => (int) $post_id, 'created_gmt' => gmdate( 'Y-m-d H:i:s' ), 'user_id' => get_current_user_id(), 'reason' => $reason, 'values' => samcp_seo_values( $post_id ) ) ); update_option( 'samcp_seo_snapshots', array_slice( $items, 0, 50 ), false ); return $id; }
function samcp_validate_seo_values( $values ) { if ( isset( $values['canonical'] ) && '' !== $values['canonical'] && ! esc_url_raw( $values['canonical'], array( 'http', 'https' ) ) ) { return new WP_Error( 'samcp_seo_canonical_invalid', __( 'Canonical URL must use HTTP or HTTPS.', 'site-abilities-mcp' ) ); } if ( ! empty( $values['og_image_id'] ) && ( 'attachment' !== get_post_type( absint( $values['og_image_id'] ) ) || ! wp_attachment_is_image( absint( $values['og_image_id'] ) ) ) ) { return new WP_Error( 'samcp_seo_image_invalid', __( 'Open Graph image ID must identify an image attachment.', 'site-abilities-mcp' ) ); } return true; }
function samcp_write_seo_values( $post_id, $values ) { foreach ( samcp_seo_keys() as $field => $key ) { if ( ! array_key_exists( $field, $values ) ) { continue; } $value = $values[ $field ]; if ( 'canonical' === $field && '' !== $value ) { $value = esc_url_raw( $value, array( 'http', 'https' ) ); } elseif ( 'og_image_id' === $field ) { $value = absint( $value ); } elseif ( 'noindex' === $field ) { $value = $value ? '1' : ''; } else { $value = sanitize_text_field( $value ); } if ( '' === $value || 0 === $value ) { delete_post_meta( $post_id, $key ); } else { update_post_meta( $post_id, $key, $value ); } } return true; }
function samcp_update_seo( $input ) {
	$post = samcp_find_seo_post( $input['post_id'] ); if ( is_wp_error( $post ) ) { return $post; }
	if ( empty( $input['confirmation'] ) || 'UPDATE_SEO' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit UPDATE_SEO confirmation is required.', 'site-abilities-mcp' ) ); }
	$current = samcp_seo_values( $post->ID ); if ( ! hash_equals( samcp_seo_hash( $current ), strtolower( (string) $input['expected_seo_sha256'] ) ) ) { return new WP_Error( 'samcp_seo_changed', __( 'SEO metadata changed after it was read. Read it again before retrying.', 'site-abilities-mcp' ) ); }
	$changes = array_intersect_key( $input, samcp_seo_keys() ); if ( ! $changes ) { return new WP_Error( 'samcp_no_changes', __( 'No SEO changes were supplied.', 'site-abilities-mcp' ) ); } $validation = samcp_validate_seo_values( $changes ); if ( is_wp_error( $validation ) ) { return $validation; }
	$snapshot = samcp_save_seo_snapshot( $post->ID, 'before_update' ); $result = samcp_write_seo_values( $post->ID, $changes ); return is_wp_error( $result ) ? $result : samcp_format_seo( $post->ID, $snapshot );
}
function samcp_list_seo_snapshots( $input ) { $items = array_filter( get_option( 'samcp_seo_snapshots', array() ), static function ( $item ) { return current_user_can( 'edit_post', absint( $item['post_id'] ) ); } ); if ( ! empty( $input['post_id'] ) ) { $items = array_filter( $items, static function ( $item ) use ( $input ) { return absint( $item['post_id'] ) === absint( $input['post_id'] ); } ); } return array_values( array_map( static function ( $item ) { unset( $item['values'] ); return $item; }, $items ) ); }
function samcp_restore_seo_snapshot( $input ) {
	if ( empty( $input['confirmation'] ) || 'RESTORE_SEO_SNAPSHOT' !== $input['confirmation'] ) { return new WP_Error( 'samcp_confirmation_required', __( 'Explicit RESTORE_SEO_SNAPSHOT confirmation is required.', 'site-abilities-mcp' ) ); }
	$snapshot = null; foreach ( get_option( 'samcp_seo_snapshots', array() ) as $candidate ) { if ( hash_equals( (string) $candidate['id'], (string) $input['snapshot_id'] ) ) { $snapshot = $candidate; break; } } if ( ! $snapshot ) { return new WP_Error( 'samcp_seo_snapshot_not_found', __( 'The requested SEO snapshot was not found.', 'site-abilities-mcp' ) ); }
	$current = samcp_seo_values( $snapshot['post_id'] ); if ( ! hash_equals( samcp_seo_hash( $current ), strtolower( (string) $input['expected_seo_sha256'] ) ) ) { return new WP_Error( 'samcp_seo_changed', __( 'SEO metadata changed after it was read. Read it again before retrying.', 'site-abilities-mcp' ) ); }
	$validation = samcp_validate_seo_values( $snapshot['values'] ); if ( is_wp_error( $validation ) ) { return $validation; } samcp_save_seo_snapshot( $snapshot['post_id'], 'before_restore' ); foreach ( samcp_seo_keys() as $key ) { delete_post_meta( $snapshot['post_id'], $key ); } $result = samcp_write_seo_values( $snapshot['post_id'], $snapshot['values'] ); return is_wp_error( $result ) ? $result : samcp_format_seo( $snapshot['post_id'] );
}

function samcp_filter_document_title( $title ) { if ( is_singular( samcp_seo_supported_types() ) && ! samcp_standard_seo_active() ) { $custom = get_post_meta( get_queried_object_id(), '_samcp_seo_title', true ); if ( $custom ) { return $custom; } } return $title; }
add_filter( 'pre_get_document_title', 'samcp_filter_document_title', 20 );
function samcp_filter_canonical( $url, $post ) { if ( ! samcp_standard_seo_active() && $post ) { $custom = get_post_meta( $post->ID, '_samcp_seo_canonical', true ); if ( $custom ) { return $custom; } } return $url; }
add_filter( 'get_canonical_url', 'samcp_filter_canonical', 20, 2 );
function samcp_filter_robots( $robots ) { if ( is_singular( samcp_seo_supported_types() ) && ! samcp_standard_seo_active() && get_post_meta( get_queried_object_id(), '_samcp_seo_noindex', true ) ) { $robots['noindex'] = true; unset( $robots['index'] ); } return $robots; }
add_filter( 'wp_robots', 'samcp_filter_robots' );
function samcp_output_seo_meta() { if ( ! is_singular( samcp_seo_supported_types() ) || samcp_standard_seo_active() ) { return; } $id = get_queried_object_id(); $values = samcp_seo_values( $id ); if ( $values['description'] ) { echo '<meta name="description" content="' . esc_attr( $values['description'] ) . '">' . "\n"; } $og_title = $values['og_title'] ? $values['og_title'] : $values['title']; $og_description = $values['og_description'] ? $values['og_description'] : $values['description']; if ( $og_title ) { echo '<meta property="og:title" content="' . esc_attr( $og_title ) . '">' . "\n"; } if ( $og_description ) { echo '<meta property="og:description" content="' . esc_attr( $og_description ) . '">' . "\n"; } if ( $values['og_image_id'] ) { $url = wp_get_attachment_url( $values['og_image_id'] ); if ( $url ) { echo '<meta property="og:image" content="' . esc_url( $url ) . '">' . "\n"; } } }
add_action( 'wp_head', 'samcp_output_seo_meta', 5 );
