<?php
/** Read-only WPBakery structure analysis and change preview. */

if ( ! defined( 'ABSPATH' ) ) { exit; }

function samcp_register_wpbakery_category() { if ( function_exists( 'wp_register_ability_category' ) ) { wp_register_ability_category( 'site-abilities-wpbakery', array( 'label' => __( 'Site WPBakery', 'site-abilities-mcp' ), 'description' => __( 'Analyzes shortcode-backed layouts before page or content abilities are used.', 'site-abilities-mcp' ) ) ); } }
add_action( 'wp_abilities_api_categories_init', 'samcp_register_wpbakery_category' );

function samcp_wpbakery_analysis_schema() { return array( 'type' => 'object', 'required' => array( 'post_id', 'post_type', 'content_sha256', 'uses_wpbakery', 'shortcode_counts', 'warnings' ), 'properties' => array( 'post_id' => array( 'type' => 'integer' ), 'post_type' => array( 'type' => 'string' ), 'content_sha256' => array( 'type' => 'string' ), 'uses_wpbakery' => array( 'type' => 'boolean' ), 'shortcode_counts' => array( 'type' => 'object' ), 'warnings' => array( 'type' => 'array', 'items' => array( 'type' => 'string' ) ), 'proposed_content_sha256' => array( 'type' => 'string' ), 'added_shortcodes' => array( 'type' => 'object' ), 'removed_shortcodes' => array( 'type' => 'object' ), 'length_delta' => array( 'type' => 'integer' ) ) ); }
function samcp_register_wpbakery_abilities() {
	if ( ! function_exists( 'wp_register_ability' ) ) { return; }
	wp_register_ability( 'site-abilities/analyze-wpbakery-content', array( 'label' => __( 'Analyze WPBakery content', 'site-abilities-mcp' ), 'description' => __( 'Reads shortcode structure and warnings. It does not open or control the visual drag-and-drop editor.', 'site-abilities-mcp' ), 'category' => 'site-abilities-wpbakery', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'post_id' ), 'properties' => array( 'post_id' => array( 'type' => 'integer', 'minimum' => 1 ) ) ), 'output_schema' => samcp_wpbakery_analysis_schema(), 'execute_callback' => 'samcp_analyze_wpbakery_content', 'permission_callback' => 'samcp_can_read_wpbakery_content', 'meta' => samcp_ability_meta( true, false, true ) ) );
	wp_register_ability( 'site-abilities/preview-wpbakery-replacement', array( 'label' => __( 'Preview WPBakery content replacement', 'site-abilities-mcp' ), 'description' => __( 'Compares existing and proposed shortcode layouts without writing. Use the guarded page or content update ability only after reviewing this preview.', 'site-abilities-mcp' ), 'category' => 'site-abilities-wpbakery', 'input_schema' => array( 'type' => 'object', 'additionalProperties' => false, 'required' => array( 'post_id', 'proposed_content' ), 'properties' => array( 'post_id' => array( 'type' => 'integer', 'minimum' => 1 ), 'proposed_content' => array( 'type' => 'string' ) ) ), 'output_schema' => samcp_wpbakery_analysis_schema(), 'execute_callback' => 'samcp_preview_wpbakery_replacement', 'permission_callback' => 'samcp_can_read_wpbakery_content', 'meta' => samcp_ability_meta( true, false, true ) ) );
}
add_action( 'wp_abilities_api_init', 'samcp_register_wpbakery_abilities' );

function samcp_can_read_wpbakery_content( $input ) { return ! empty( $input['post_id'] ) && current_user_can( 'read_post', absint( $input['post_id'] ) ); }
function samcp_wpbakery_post( $id ) { $post = get_post( absint( $id ) ); $allowed = array_merge( array( 'page', 'product' ), samcp_allowed_content_types() ); return $post && in_array( $post->post_type, $allowed, true ) ? $post : new WP_Error( 'samcp_wpbakery_post_not_found', __( 'The requested supported content item was not found.', 'site-abilities-mcp' ) ); }
function samcp_shortcode_counts( $content ) { $counts = array(); if ( preg_match_all( '/\[(?!\/)([A-Za-z][A-Za-z0-9_-]*)(?:\s|\]|\/)/', (string) $content, $matches ) ) { foreach ( $matches[1] as $tag ) { $tag = strtolower( $tag ); $counts[ $tag ] = isset( $counts[ $tag ] ) ? $counts[ $tag ] + 1 : 1; } } ksort( $counts ); return $counts; }
function samcp_wpbakery_warnings( $content, $counts ) { $warnings = array(); $open_rows = isset( $counts['vc_row'] ) ? $counts['vc_row'] : 0; $close_rows = preg_match_all( '/\[\/vc_row\]/i', $content ); if ( $open_rows !== $close_rows ) { $warnings[] = sprintf( __( 'Unbalanced vc_row shortcodes: %1$d opening and %2$d closing tags.', 'site-abilities-mcp' ), $open_rows, $close_rows ); } $open_columns = isset( $counts['vc_column'] ) ? $counts['vc_column'] : 0; $close_columns = preg_match_all( '/\[\/vc_column\]/i', $content ); if ( $open_columns !== $close_columns ) { $warnings[] = sprintf( __( 'Unbalanced vc_column shortcodes: %1$d opening and %2$d closing tags.', 'site-abilities-mcp' ), $open_columns, $close_columns ); } if ( false !== stripos( $content, '<script' ) ) { $warnings[] = __( 'Content contains a script element; review it manually before any update.', 'site-abilities-mcp' ); } return $warnings; }
function samcp_wpbakery_analysis( $post, $content = null ) { $content = null === $content ? (string) $post->post_content : (string) $content; $counts = samcp_shortcode_counts( $content ); $uses = false; foreach ( array_keys( $counts ) as $tag ) { if ( 0 === strpos( $tag, 'vc_' ) || 0 === strpos( $tag, 'ult_' ) ) { $uses = true; break; } } return array( 'post_id' => (int) $post->ID, 'post_type' => (string) $post->post_type, 'content_sha256' => hash( 'sha256', $content ), 'uses_wpbakery' => $uses, 'shortcode_counts' => $counts, 'warnings' => samcp_wpbakery_warnings( $content, $counts ) ); }
function samcp_analyze_wpbakery_content( $input ) { $post = samcp_wpbakery_post( $input['post_id'] ); return is_wp_error( $post ) ? $post : samcp_wpbakery_analysis( $post ); }
function samcp_preview_wpbakery_replacement( $input ) { $post = samcp_wpbakery_post( $input['post_id'] ); if ( is_wp_error( $post ) ) { return $post; } $current = samcp_shortcode_counts( $post->post_content ); $proposed = samcp_wpbakery_analysis( $post, $input['proposed_content'] ); $proposed['content_sha256'] = hash( 'sha256', (string) $post->post_content ); $proposed['proposed_content_sha256'] = hash( 'sha256', (string) $input['proposed_content'] ); $proposed['added_shortcodes'] = array(); $proposed['removed_shortcodes'] = array(); foreach ( array_unique( array_merge( array_keys( $current ), array_keys( $proposed['shortcode_counts'] ) ) ) as $tag ) { $delta = ( isset( $proposed['shortcode_counts'][ $tag ] ) ? $proposed['shortcode_counts'][ $tag ] : 0 ) - ( isset( $current[ $tag ] ) ? $current[ $tag ] : 0 ); if ( $delta > 0 ) { $proposed['added_shortcodes'][ $tag ] = $delta; } elseif ( $delta < 0 ) { $proposed['removed_shortcodes'][ $tag ] = abs( $delta ); } } $proposed['length_delta'] = strlen( (string) $input['proposed_content'] ) - strlen( (string) $post->post_content ); return $proposed; }
